### ISSUE TITLE
Theory part

### ISSUE THREAD

**Issue by YashasKumar** [alok1929/codigo#19]

**Comment by alok1929** [comment]
1. first topic to be discussed - oops concepts
2. history of c++
3. what is c++
4. uses of c++ 
5. a link to most asked questions on c++
6. how to install c++
7. insult turbo c++
8. how to install on windows
9. how to install on linux

**the installation should have images**

**Comment by YashasKumar** [comment]
Why mention me?

**Comment by alok1929** [comment]
### To know who is assigned to which issue 
 and it keeps it more organised as well

**Comment by YashasKumar** [comment]
Respected Alok,
I am writing this email to tell you that I have some ideas for the homepage
of the website.

See, we can maybe write what is coding/programming and then we can give an
introduction about programming languages and everything.
And then we can be like you can learn some of them right here antha and
then we can direct them to the course.
I am just talking about the homepage, other stuff we can decide later. It i
s better to go step by step no? So I told first for homepage.

**Comment by YashasKumar** [comment]
And also i am almost done with the beginners programs. After finishing i
will call you

**Comment by alok1929** [comment]
yea sure , and we can talk about that idea you have as well

**Comment by alok1929** [comment]
https://youtu.be/8Bx9e8uk8ko
