### ISSUE TITLE
Python Programs

### ISSUE THREAD

**Issue by alok1929** [alok1929/codigo#20]
things to be done :

1. create a branch for python
2. write up beginner programs on python

**Comment by Abhicoder03** [comment]
Hey, Could you assign this to me. I can do this.

**Comment by alok1929** [comment]
yea sure  ,you have to write the beginner programs  given in this text file
[https://github.com/alok1929/codigo/blob/master/cppProgramming/beginnerPrograms.txt](url)
writing the python version of all these programs would be enough for now

**Comment by Abhicoder03** [comment]
Which programs?

**Comment by alok1929** [comment]
![github](https://user-images.githubusercontent.com/51386198/117317540-38c2e400-aea7-11eb-98ea-510b8621f783.png)

These programs .

**Comment by Abhicoder03** [comment]
Okay.

**Comment by alok1929** [comment]
@Abhicoder03  are u still working on this ? if not , please do tell

**Comment by Abhicoder03** [comment]
@alok1929 I'll submit all the programs by tomorrow.

**Comment by alok1929** [comment]
@YashasKumar create a pull request for the python programs as soon as possible

**Comment by YashasKumar** [comment]
Okay sure!
