### ISSUE TITLE
Adding a python category on the website  

### ISSUE THREAD

**Issue by alok1929** [alok1929/codigo#21]
### A python category should be made on the website with subtopics as follows :

> what is python ?
> why use python ?
> installing python on windows and Linux with images

**Comment by YashasKumar** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by alok1929** [comment]
@YashasKumar i have assigned it to you

**Comment by YashasKumar** [comment]
Respected Alok,
I am writing this email for a reason.
I have done the theory part of the python black and have pushed it. See if
I missed out any point and inform me. I have not added any graphics because
I do not know CSS. Make sure you look into that.
Thank you!

**Comment by alok1929** [comment]
Respected Yashoes kumaranna,
i havent looked into it , but i am sure you havent missed out on anything
welcome
also you dont have to be so formal
