### ISSUE TITLE
A sidebar for the website

### ISSUE THREAD

**Issue by alok1929** [alok1929/codigo#7]

**Comment by alok1929** [comment]
the website should look like this [
![codigo](https://user-images.githubusercontent.com/51386198/112757245-8d508500-9006-11eb-8450-f79babdd62c8.png)
](url)

**Comment by harshb55** [comment]
![1617131377095](https://user-images.githubusercontent.com/80906400/113043567-3f7c7e00-91ba-11eb-8969-9104eda528bd.png)

**Comment by harshb55** [comment]
JUST A PICTURE OF WEBSITE.

**Comment by alok1929** [comment]
Okay thanks harshith
